
[[plugins]]
package = "@netlify/plugin-sitemap"

[build]
  publish = "dist"

# SEO and Performance Headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirects for SPA routing
[[redirects]]
  from = "/auth"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/products"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/products/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/laptops"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/desktops"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/components"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/peripherals"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/gaming"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/audio"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/printers"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/phones"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/refurbished-phones"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/categories/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/cart"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/my-orders"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/flash-sales"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/blog/*"
  to = "/index.html"
  status = 200

# Catch-all redirect for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
