// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://axihtddcqfotuyelfdqj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF4aWh0ZGRjcWZvdHV5ZWxmZHFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1NzY5MzYsImV4cCI6MjA2ODE1MjkzNn0.otx4djeBd8E7cJ7NOqMI5xTsN9Ll5Q8U13v7Fv3WQNM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});